data:
    word_min_count: 2
    max_vocab_size: 100000
    max_sentences: 120000
    train_ratio: 0.9
    test_ratio: 0.05
    val_ratio: 0.05
    min_sentence_len: 4
    max_sentence_len: 50
    max_word_len: 30
model:
    embedding:
        type: word
        word:
            dim: 125
        char:
            type: LSTM
            dim: 25
            LSTM:
                hidden_size: 50
                num_layers: 1
                dropout: 0.3
            GRU:
                hidden_size: 50
                num_layers: 1
                dropout: 0.3
    encoder:
        type: GRU
        num_layers: 2
        hidden_size: 125
        dropout: 0.3
training:
    optimizer:
        name: adam
        lr: 0.001
    grad_clip: 5.0
    epochs: 10
    log_interval: 1
    batch_size: 32
