data:
    word_min_count: 2
    vocab_size: 100000
    num_train_sentences: 80000
    num_valid_sentences: 5000
    num_test_sentences: 5000
    min_sentence_len: 3
    max_sentence_len: 100
model:
    embedding:
        type: word
        word:
            dim: 125
    encoder:
        type: GRU
        num_layers: 2
        hidden_size: 125
        dropout: 0.3
training:
    optimizer:
        name: adam
        lr: 0.001
    grad_clip: 5.0
    epochs: 1
    log_interval: 1
    batch_size: 32